// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using corsosharp.Data;

#nullable disable

namespace corsosharp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212140623_aggiuntocaampocodicefiscale")]
    partial class aggiuntocaampocodicefiscale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("corsosharp.Models.AnagrafiaDipendente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DataAssunzione")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDimissione")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Eta")
                        .HasColumnType("int");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Stipendio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid?>("TipologiaLavoroId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tipologia_lavoro_id");

                    b.Property<string>("codiceFiscale")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TipologiaLavoroId");

                    b.ToTable("anagrafica_dipendente");
                });

            modelBuilder.Entity("corsosharp.Models.GiornataLavorativa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Azienda")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DipendenteId")
                        .HasColumnType("char(36)")
                        .HasColumnName("dipendente_id");

                    b.Property<string>("Mansione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Ora")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("OraFine")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("OraInizio")
                        .HasColumnType("time(6)");

                    b.Property<decimal>("OreLavorate")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("ore_lavorate");

                    b.Property<string>("TitoloNota")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DipendenteId");

                    b.ToTable("giornate_lavorative");
                });

            modelBuilder.Entity("corsosharp.Models.TipologiaLavoro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tipologia_lavoro");
                });

            modelBuilder.Entity("corsosharp.Models.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("corsosharp.Models.AnagrafiaDipendente", b =>
                {
                    b.HasOne("corsosharp.Models.TipologiaLavoro", "TipologiaLavoro")
                        .WithMany()
                        .HasForeignKey("TipologiaLavoroId");

                    b.Navigation("TipologiaLavoro");
                });

            modelBuilder.Entity("corsosharp.Models.GiornataLavorativa", b =>
                {
                    b.HasOne("corsosharp.Models.AnagrafiaDipendente", "Dipendente")
                        .WithMany("GiornateLavorative")
                        .HasForeignKey("DipendenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dipendente");
                });

            modelBuilder.Entity("corsosharp.Models.AnagrafiaDipendente", b =>
                {
                    b.Navigation("GiornateLavorative");
                });
#pragma warning restore 612, 618
        }
    }
}
